/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import objects.*;
import model.*;

/**
 *
 * @author Airam
 */
public class Inventario extends javax.swing.JFrame {

    private Usuario u;
    
    /**
     * Creates new form Inventario
     */
    public Inventario( Usuario u ) {
        initComponents();
        this.u = u;
        setLocationRelativeTo(null);
        setResizable(false);
        Proveedor pr = null;
        proveedores();
        llenarTablaProductos( Model.getProductos() );
    }

    public Inventario( ) {
        initComponents();
        this.u = new Usuario(0, null, null, null, true, null, null);
        setLocationRelativeTo(null);
        setResizable(false);
        Proveedor pr = null;
        proveedores();
        llenarTablaProductos( Model.getProductos() );
    }
    
    private ArrayList<Proveedor> proveedores(){
        ArrayList<Proveedor> pl = new ArrayList<>();
        for(Proveedor p : Model.getProveedor()){
            if(!p.getNombre().endsWith("-P")){    
                proveedores.addItem(p.getNombre());
                pl.add(p);
            }
        }
        return pl;
    }
    
    private void llenarTablaProductos(ArrayList<Producto> lista){
        DefaultTableModel modelo = new DefaultTableModel();
        tabla.setModel(modelo);
        int cantidadColumnas = 6;
          
        modelo.addColumn("ID");
        modelo.addColumn("Modelo");
        modelo.addColumn("Tipo");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Costo");
        modelo.addColumn("Precio");  
        int[] anchos ={40,70,70,90,80,80};
          
        for (int x =0; x < cantidadColumnas; x++  ){
            tabla.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
        }
        
        for( Producto p : lista){
            Object[] fila = new Object[cantidadColumnas];
            fila[0] = p.getIdPro();
            fila[1] = p.getModeloPro();
            if(p.isPerfo())
                fila[2] = "Perforación";
            else
                fila[2] = p.getTipoPro();
            fila[3] = p.getCantidadPro();
            fila[4] = p.getCostoPro(); 
            fila[5] = p.getPrecioPro();
            modelo.addRow(fila);
        }
    }
      
    private void limpiar(){
        modelo.setText("");
        tipo.setText("");
        costo.setText("");
        precio.setText("");
        cantidad.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        proveedores = new javax.swing.JComboBox<>();
        salir = new javax.swing.JToggleButton();
        nombre1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        eliminar = new javax.swing.JToggleButton();
        editar = new javax.swing.JToggleButton();
        nuevo = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setToolTipText("INVENTARIO");
        jPanel3.setMaximumSize(new java.awt.Dimension(920, 590));
        jPanel3.setMinimumSize(new java.awt.Dimension(920, 590));
        jPanel3.setPreferredSize(new java.awt.Dimension(920, 590));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modelo: ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(631, 129, 90, 26);
        jPanel3.add(costo);
        costo.setBounds(734, 218, 137, 20);
        jPanel3.add(tipo);
        tipo.setBounds(733, 174, 138, 20);

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo: ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(631, 173, 90, 26);

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cantidad: ");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(631, 305, 100, 26);
        jPanel3.add(modelo);
        modelo.setBounds(733, 130, 138, 20);
        jPanel3.add(precio);
        precio.setBounds(734, 262, 137, 20);

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Precio: ");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(631, 261, 100, 26);

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Costo:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(631, 217, 80, 26);
        jPanel3.add(cantidad);
        cantidad.setBounds(732, 306, 137, 20);

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Proveedor:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(65, 65, 100, 26);

        proveedores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                proveedoresItemStateChanged(evt);
            }
        });
        proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedoresMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proveedoresMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                proveedoresMousePressed(evt);
            }
        });
        proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresActionPerformed(evt);
            }
        });
        jPanel3.add(proveedores);
        proveedores.setBounds(167, 64, 160, 26);

        salir.setBackground(new java.awt.Color(0, 0, 0));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresarboton.png"))); // NOI18N
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel3.add(salir);
        salir.setBounds(40, 370, 60, 50);

        nombre1.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        nombre1.setForeground(new java.awt.Color(255, 255, 255));
        nombre1.setText("Inventario");
        jPanel3.add(nombre1);
        nombre1.setBounds(631, 50, 240, 38);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Tipo", "Cantidad", "Costo", "Precio"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(40, 129, 452, 202);

        eliminar.setBackground(new java.awt.Color(0, 0, 0));
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trashpeque.png"))); // NOI18N
        eliminar.setBorder(null);
        eliminar.setContentAreaFilled(false);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar);
        eliminar.setBounds(830, 377, 41, 39);

        editar.setBackground(new java.awt.Color(0, 0, 0));
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editboton.png"))); // NOI18N
        editar.setBorder(null);
        editar.setContentAreaFilled(false);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        jPanel3.add(editar);
        editar.setBounds(734, 377, 41, 39);

        nuevo.setBackground(new java.awt.Color(0, 0, 0));
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        nuevo.setBorder(null);
        nuevo.setContentAreaFilled(false);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel3.add(nuevo);
        nuevo.setBounds(631, 377, 41, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoI.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(-10, 0, 940, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        if(this.u.getRango()){
            dispose();
            new MenuP().setVisible(true);
        } else {
            dispose();
            new MenuS(u).setVisible(true);
        }
    }//GEN-LAST:event_salirActionPerformed

    private void proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedoresActionPerformed

    private void proveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresMousePressed

    }//GEN-LAST:event_proveedoresMousePressed

    private void proveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresMouseExited

    }//GEN-LAST:event_proveedoresMouseExited

    private void proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresMouseClicked

    }//GEN-LAST:event_proveedoresMouseClicked

    private void proveedoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_proveedoresItemStateChanged
        for( Proveedor pr : Model.getProveedor() ){
            if(proveedores.getSelectedItem().toString().equals(pr.getNombre())){
                llenarTablaProductos(Model.getProductos(pr.getId()));
            }
        }
        limpiar();
    }//GEN-LAST:event_proveedoresItemStateChanged

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try{    
            Model.eliminarProducto(Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 0).toString()));
            for( Proveedor pr : Model.getProveedor() ){
                if(proveedores.getSelectedItem().toString().equals(pr.getNombre())){
                    llenarTablaProductos(Model.getProductos(pr.getId()));
                }
            }
            limpiar();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "No a seleccionado nada." );
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        try{    
            Producto p = new Producto(
                Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 0).toString()),
                modelo.getText(),
                tipo.getText(),
                Integer.parseInt(cantidad.getText()),
                Double.parseDouble(precio.getText()),
                Model.buscarProveedor(proveedores.getSelectedItem().toString()),
                Double.parseDouble(costo.getText()),
                false
            );
            Model.modificarProducto(p);
            for( Proveedor pr : Model.getProveedor() ){
                if(proveedores.getSelectedItem().toString().equals(pr.getNombre())){
                    llenarTablaProductos(Model.getProductos(pr.getId()));
                }
            }
            limpiar();
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El formato en los campos es incorrecto." );
        } catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "No a seleccionado nada." );
        }
    }//GEN-LAST:event_editarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        dispose();
        new RegistroProducto(this.u).setVisible(true);
    }//GEN-LAST:event_nuevoActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        Producto p = Model.buscarProducto(Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 0).toString()));
        modelo.setText(p.getModeloPro());
        tipo.setText(p.getTipoPro());
        cantidad.setText(Integer.toString(p.getCantidadPro()));
        precio.setText(Double.toString(p.getPrecioPro()));
        costo.setText(Double.toString(p.getCostoPro()));
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awp.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField costo;
    private javax.swing.JToggleButton editar;
    private javax.swing.JToggleButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modelo;
    private javax.swing.JLabel nombre1;
    private javax.swing.JToggleButton nuevo;
    private javax.swing.JTextField precio;
    private javax.swing.JComboBox<String> proveedores;
    private javax.swing.JToggleButton salir;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
