/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objects.*;
import model.*;
import model.util.*;

/**
 *
 * @author edera
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        setLocationRelativeTo(null);
        llenarAnio(anioDiario);
        llenarAnio(anioMensual);
        llenarAnio(anioAnual);
        llenarDias();
        totalDiario.setText("0");
        totalMensual.setText("0");
        totalAnual.setText("0");
    }

    private void llenarAnio(javax.swing.JComboBox<String> anio){
        if(TicketDB.getMinAnio() != 0 && TicketDB.getMaxAnio() != 0){
            for(int i = TicketDB.getMinAnio(); i <= TicketDB.getMaxAnio(); i++){
                anio.addItem(Integer.toString(i));
            }
        }
    }
    
    private void llenarDias(){
        if(getMesSelected(mesDiario)%2 == 0){
            if(getMesSelected(mesDiario) != 2){   
                for(int i = 1; i <= 30; ++i){
                    diaDiario.addItem(Integer.toString(i));
                }
            } else {
                for(int i = 1; i <= 28; ++i){
                    diaDiario.addItem(Integer.toString(i));
                }
            }
        } else {
            for(int i = 1; i <= 31; ++i){
                diaDiario.addItem(Integer.toString(i));
            }
        }
    }
    
    private void llenarTablaTicket(javax.swing.JTable tabla, ArrayList<Ticket> lista){
        DefaultTableModel modelo = new DefaultTableModel();
        tabla.setModel(modelo);
        int cantidadColumnas = 6;
          
        modelo.addColumn("Num. Ticket");
        modelo.addColumn("Fecha");
        modelo.addColumn("Tatuador");
        modelo.addColumn("Perforador");
        modelo.addColumn("Venta Producto");
        modelo.addColumn("Total");  
        int[] anchos ={70,80,130,100,40,60};
          
        for (int x =0; x < cantidadColumnas; x++  ){
            tabla.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
        }
        
        for( Ticket t : lista){
            Object[] fila = new Object[cantidadColumnas];
            fila[0] = t.getId();
            fila[1] = Integer.toString(t.getDia())+" / "+Integer.toString(t.getMes())+" / "+Integer.toString(t.getAnio());
           
            if(t.getTatuador() != null){
                fila[2] = t.getTatuador().getNombre()+" "+t.getTatuador().getAp_pat()+" "+t.getTatuador().getAp_mat();
            } else {
                fila[2] = "";
            }
            
            if(t.getPerforador() != null){
                fila[3] = t.getPerforador().getNombre();
            } else {
                fila[3] = "";
            }
            
            if(t.isProd()){
                fila[4] = "Sí";
            } else {
                fila[4] = "No";
            }
            fila[5] = t.getTotal();
            modelo.addRow(fila);
        }
    }

    private int getMesSelected(javax.swing.JComboBox<String> mes){
        switch(mes.getSelectedItem().toString()){
            case "Enero":
                return 1;
            case "Febrero":
                return 2;
            case "Marzo":
                return 3;
            case "Abril":
                return 4;
            case "Mayo":
                return 5;
            case "Junio":
                return 6;
            case "Julio":
                return 7;
            case "Agosto":
                return 8;
            case "Septiembre":
                return 9;
            case "Octubre":
                return 10;
            case "Noviembre":
                return 11;
            case "Diciembre":
                return 12;
            default:
                return 0;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        mesDiario = new javax.swing.JComboBox<>();
        detallesDiario = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaDiario = new javax.swing.JTable();
        buscarDiario = new javax.swing.JToggleButton();
        anioDiario = new javax.swing.JComboBox<>();
        diaDiario = new javax.swing.JComboBox<>();
        comisionesDiario = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        totalDiario = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        anioMensual = new javax.swing.JComboBox<>();
        totalMensual = new javax.swing.JLabel();
        detallesMensual = new javax.swing.JToggleButton();
        mesMensual = new javax.swing.JComboBox<>();
        buscarMensual = new javax.swing.JToggleButton();
        comisionesMensual = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaMensual = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        anioAnual = new javax.swing.JComboBox<>();
        buscarAnual = new javax.swing.JToggleButton();
        detallesAnual = new javax.swing.JToggleButton();
        comisionesAnual = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        totalAnual = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaAnual = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTES");
        setMaximumSize(new java.awt.Dimension(920, 590));
        setMinimumSize(new java.awt.Dimension(920, 590));
        setPreferredSize(new java.awt.Dimension(920, 590));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reportes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 50, 177, 49);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seleccione un mes:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 60, 160, 22);

        mesDiario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesDiario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mesDiarioItemStateChanged(evt);
            }
        });
        jPanel4.add(mesDiario);
        mesDiario.setBounds(260, 60, 120, 20);

        detallesDiario.setText("Ver detalles");
        detallesDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesDiarioActionPerformed(evt);
            }
        });
        jPanel4.add(detallesDiario);
        detallesDiario.setBounds(590, 60, 110, 23);

        tablaDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Num. Ticket", "Fecha", "Tatuador", "Perforador", "Venta Productos", "Total"
            }
        ));
        jScrollPane5.setViewportView(tablaDiario);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(140, 100, 510, 164);

        buscarDiario.setText("Buscar");
        buscarDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDiarioActionPerformed(evt);
            }
        });
        jPanel4.add(buscarDiario);
        buscarDiario.setBounds(500, 60, 80, 23);

        anioDiario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        anioDiario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                anioDiarioItemStateChanged(evt);
            }
        });
        jPanel4.add(anioDiario);
        anioDiario.setBounds(390, 60, 100, 20);

        jPanel4.add(diaDiario);
        diaDiario.setBounds(190, 60, 50, 22);

        comisionesDiario.setText("Comisiones");
        comisionesDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comisionesDiarioActionPerformed(evt);
            }
        });
        jPanel4.add(comisionesDiario);
        comisionesDiario.setBounds(630, 280, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("$");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(80, 290, 10, 22);

        totalDiario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalDiario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(totalDiario);
        totalDiario.setBounds(90, 290, 120, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(30, 290, 70, 22);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoI.jpg"))); // NOI18N
        jLabel27.setText("jLabel1");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(0, 0, 2598, 1440);

        jTabbedPane1.addTab("Diario", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(null);

        anioMensual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        anioMensual.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                anioMensualItemStateChanged(evt);
            }
        });
        jPanel5.add(anioMensual);
        anioMensual.setBounds(350, 60, 130, 20);

        totalMensual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalMensual.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(totalMensual);
        totalMensual.setBounds(90, 290, 120, 22);

        detallesMensual.setText("Ver detalles");
        detallesMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesMensualActionPerformed(evt);
            }
        });
        jPanel5.add(detallesMensual);
        detallesMensual.setBounds(590, 60, 120, 23);

        mesMensual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesMensual.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mesMensualItemStateChanged(evt);
            }
        });
        jPanel5.add(mesMensual);
        mesMensual.setBounds(200, 60, 130, 20);

        buscarMensual.setText("Buscar");
        buscarMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMensualActionPerformed(evt);
            }
        });
        jPanel5.add(buscarMensual);
        buscarMensual.setBounds(500, 60, 80, 23);

        comisionesMensual.setText("Comisiones");
        comisionesMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comisionesMensualActionPerformed(evt);
            }
        });
        jPanel5.add(comisionesMensual);
        comisionesMensual.setBounds(630, 280, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Seleccione un mes:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(30, 60, 156, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total:");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(30, 290, 70, 22);

        tablaMensual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Num. Ticket", "Fecha", "Tatuador", "Perforador", "Venta Productos", "Total"
            }
        ));
        jScrollPane6.setViewportView(tablaMensual);

        jPanel5.add(jScrollPane6);
        jScrollPane6.setBounds(140, 100, 510, 164);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("$");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(80, 290, 10, 22);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoI.jpg"))); // NOI18N
        jLabel26.setText("jLabel1");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(0, 0, 2598, 1440);

        jTabbedPane1.addTab("Mensual", jPanel5);

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));
        jPanel6.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seleccione un año:");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(130, 60, 153, 22);

        anioAnual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        anioAnual.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                anioAnualItemStateChanged(evt);
            }
        });
        jPanel6.add(anioAnual);
        anioAnual.setBounds(290, 60, 130, 20);

        buscarAnual.setText("Buscar");
        buscarAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAnualActionPerformed(evt);
            }
        });
        jPanel6.add(buscarAnual);
        buscarAnual.setBounds(440, 60, 90, 23);

        detallesAnual.setText("Ver detalles");
        detallesAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesAnualActionPerformed(evt);
            }
        });
        jPanel6.add(detallesAnual);
        detallesAnual.setBounds(550, 60, 100, 23);

        comisionesAnual.setText("Comisiones");
        comisionesAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comisionesAnualActionPerformed(evt);
            }
        });
        jPanel6.add(comisionesAnual);
        comisionesAnual.setBounds(630, 280, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(30, 290, 70, 22);

        totalAnual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalAnual.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(totalAnual);
        totalAnual.setBounds(90, 290, 120, 22);

        tablaAnual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Num. Ticket", "Fecha", "Tatuador", "Perforador", "Venta Productos", "Total"
            }
        ));
        jScrollPane7.setViewportView(tablaAnual);

        jPanel6.add(jScrollPane7);
        jScrollPane7.setBounds(140, 100, 510, 164);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("$");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(80, 290, 10, 22);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoI.jpg"))); // NOI18N
        jLabel25.setText("jLabel1");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(0, 0, 2598, 1440);

        jTabbedPane1.addTab("Anual", jPanel6);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 10, 760, 360);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 120, 800, 380);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresarboton.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 510, 65, 41);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoI.jpg"))); // NOI18N
        jLabel24.setText("jLabel1");
        jPanel2.add(jLabel24);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 930, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        MenuP m=new MenuP();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void detallesAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesAnualActionPerformed
        try{
            Ticket t = Model.buscarTicket(Integer.parseInt(tablaAnual.getValueAt(tablaAnual.getSelectedRow(), 0).toString()));
            dispose();
            new Detalles(t).setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado nada." );
        }
    }//GEN-LAST:event_detallesAnualActionPerformed

    private void buscarAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAnualActionPerformed
        llenarTablaTicket(tablaAnual, Model.getTickets(0, 0, Integer.parseInt(anioAnual.getSelectedItem().toString())));
        totalAnual.setText(Double.toString(Model.getTotal(0,0, Integer.parseInt(anioAnual.getSelectedItem().toString()))));
    }//GEN-LAST:event_buscarAnualActionPerformed

    private void anioAnualItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_anioAnualItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_anioAnualItemStateChanged

    private void buscarMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMensualActionPerformed
        llenarTablaTicket(tablaMensual, Model.getTickets(0, getMesSelected(mesMensual), Integer.parseInt(anioMensual.getSelectedItem().toString())));
        totalMensual.setText(Double.toString(Model.getTotal(0, getMesSelected(mesMensual), Integer.parseInt(anioMensual.getSelectedItem().toString()))));
    }//GEN-LAST:event_buscarMensualActionPerformed

    private void mesMensualItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mesMensualItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mesMensualItemStateChanged

    private void detallesMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesMensualActionPerformed
        try{
            Ticket t = Model.buscarTicket(Integer.parseInt(tablaMensual.getValueAt(tablaMensual.getSelectedRow(), 0).toString()));
            dispose();
            new Detalles(t).setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado nada." );
        }
    }//GEN-LAST:event_detallesMensualActionPerformed

    private void anioMensualItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_anioMensualItemStateChanged

    }//GEN-LAST:event_anioMensualItemStateChanged

    private void anioDiarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_anioDiarioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_anioDiarioItemStateChanged

    private void buscarDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDiarioActionPerformed
        llenarTablaTicket(tablaDiario, Model.getTickets(Integer.parseInt(diaDiario.getSelectedItem().toString()), getMesSelected(mesDiario), Integer.parseInt(anioDiario.getSelectedItem().toString())));
        totalDiario.setText(Double.toString(Model.getTotal(Integer.parseInt(diaDiario.getSelectedItem().toString()), getMesSelected(mesDiario), Integer.parseInt(anioDiario.getSelectedItem().toString()))));
    }//GEN-LAST:event_buscarDiarioActionPerformed

    private void detallesDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesDiarioActionPerformed
        try{
            new Detalles(Model.buscarTicket(Integer.parseInt(tablaDiario.getValueAt(tablaDiario.getSelectedRow(), 0).toString()))).setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado nada." );
        }
    }//GEN-LAST:event_detallesDiarioActionPerformed

    private void mesDiarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mesDiarioItemStateChanged
        llenarDias();
    }//GEN-LAST:event_mesDiarioItemStateChanged

    private void comisionesMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comisionesMensualActionPerformed
        try{
            new Comisiones(0, mesMensual.getSelectedItem().toString(), Integer.parseInt(anioMensual.getSelectedItem().toString())).setVisible(true);
            dispose();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_comisionesMensualActionPerformed

    private void comisionesDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comisionesDiarioActionPerformed
        try{
            new Comisiones(Integer.parseInt(diaDiario.getSelectedItem().toString()), mesDiario.getSelectedItem().toString(), Integer.parseInt(anioDiario.getSelectedItem().toString())).setVisible(true);
            dispose();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_comisionesDiarioActionPerformed

    private void comisionesAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comisionesAnualActionPerformed
        try{
            new Comisiones(0, "", Integer.parseInt(anioAnual.getSelectedItem().toString())).setVisible(true);
            dispose();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_comisionesAnualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anioAnual;
    private javax.swing.JComboBox<String> anioDiario;
    private javax.swing.JComboBox<String> anioMensual;
    private javax.swing.JToggleButton buscarAnual;
    private javax.swing.JToggleButton buscarDiario;
    private javax.swing.JToggleButton buscarMensual;
    private javax.swing.JToggleButton comisionesAnual;
    private javax.swing.JToggleButton comisionesDiario;
    private javax.swing.JToggleButton comisionesMensual;
    private javax.swing.JToggleButton detallesAnual;
    private javax.swing.JToggleButton detallesDiario;
    private javax.swing.JToggleButton detallesMensual;
    private javax.swing.JComboBox<String> diaDiario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> mesDiario;
    private javax.swing.JComboBox<String> mesMensual;
    private javax.swing.JTable tablaAnual;
    private javax.swing.JTable tablaDiario;
    private javax.swing.JTable tablaMensual;
    private javax.swing.JLabel totalAnual;
    private javax.swing.JLabel totalDiario;
    private javax.swing.JLabel totalMensual;
    // End of variables declaration//GEN-END:variables
}
